### PR TITLE
Update to latest rise-storage version

### PR DESCRIPTION
**Pull request by donnapep**
* Update to latest rise-storage version.
* Clean up gulpfile and package.json

### CODE REVIEW

**Comment by donnapep** [comment]
@stulees Please review. Thx.

**Comment by stulees** [comment]
@donnapep :+1:

**Comment by donnapep** [comment]
@stulees Updated the following:

* `common-style` to `rv-common-style`
* Added `storage-type` to URL field component
* `rise-storage` component
* Storage modal URLs
* Widget e2e tests

The changes to `package.json` you had already reviewed but I squashed them.

Please review. Thx.

**Comment by stulees** [comment]
@donnapep :+1:

**Comment by donnapep** [comment]
@stulees Please review the last commit where I update to latest `rise-storage` and `webcomponentsjs`. I also altered the Gulpfile to only copy the files that Polymer needs.

The previous commits were my attempt to fix the build until we realized that Storage throttling was likely wreaking havoc on tests. I've put the test back in and it passed this morning. Thx.

**Comment by stulees** [comment]
@donnapep :+1:

**Pull request merged**
