### PR TITLE
Add polymer-ready event

### PR DESCRIPTION
**Pull request by donnapep**
* Add `polymer-ready` event.
* Update to latest versions of components.
* Refactor code to work with JSON response received from `rise-storage`.
* Add `fileType` attribute to `rise-storage` to return only images.
* Update Storage modal test URL.
* Add missing `webcomponents.min.js` file to build.
* Commit Production-ready files to `dist`.

### CODE REVIEW

**Comment by donnapep** [comment]
@stulees Please review. Thx.

**Comment by stulees** [comment]
@donnapep Please review, thanks

**Comment by stulees** [comment]
@donnapep Wow, I mean :+1:

**Comment by donnapep** [comment]
@stulees lol. You should have another coffee.

**Pull request merged**
